name: music-box
on:
  schedule:
    - cron: '30 10 * * *'

jobs:
  musicbox:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - run: npm install
     - name: Update
       uses: ./
       env:
          LASTFM_KEY: ${{ secrets.LASTFM_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          LFMUSERNAME: Boycottangent
          GIST_ID: ${{ secrets.GIST_ID }}
