name: music-box

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: Boycottangent/music-box@master
        env:
          LASTFM_KEY: ${{ secrets.LASTFM_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LFMUSERNAME: Boycottangent
          GIST_ID: cc94ef872818a4adbad324d0bb229082
